- name: Install Docker and some required dependencies
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - docker
    - python-pip
    - gcc

- name: Ensure Docker daemon is running
  service:
    name: docker
    state: started

- name: Install Docker Module for Python
  pip:
    name:
      - docker
      - docker-compose
    state: latest

- name: Init SSL certificates using Let's Encrypt certbot
  shell: ./utils/init_letsencrypt/index.sh
  args:
    chdir: portfolio

- name: Start (or restart) services
  docker_compose:
    project_src: ./portfolio
    files: docker-compose.prod.yml
    pull: yes

- name: Assert that services are running
  assert:
    that:
      - "nginx.portfolio_nginx.state.running"
      - "flutter.portfolio_flutter.state.running"
