# docker-compose.yml
version: '3'

services:
  nginx:
    image: petitloan/portfolio:nginx
    container_name: loanpetit_nginx
    restart: always
    depends_on:
      - certbot
      - flutter
    volumes:
      - "portfolio-certbot-conf:/etc/letsencrypt"
      - "certbot-www:/var/www/certbot"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"

  flutter:
    image: petitloan/portfolio:flutter
    container_name: loanpetit_flutter
    restart: always
    expose:
      - "80"

  certbot:
    image: certbot/certbot
    container_name: loanpetit_certbot
    restart: always
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - "portfolio-certbot-conf:/etc/letsencrypt"
      - "certbot-www:/var/www/certbot"

volumes:
  portfolio-certbot-conf:
    external: true
  certbot-www:
