# docker-compose.yml
version: '3'

services:
  nginx:
    build: 
      context: ./nginx/
      args:
        APP_ENV: dev
    image: portfolio_nginx:latest
    container_name: portfolio_nginx
    restart: always
    depends_on:
      - flutter
    ports:
      - "80:80"

  flutter:
    build: 
      context: ./flutter/
      args:
        FLUTTER_VERSION: v1.15.3
    image: portfolio_flutter:latest
    container_name: portfolio_flutter
    restart: always
    expose:
      - "80"
