# docker-compose.yml
version: '3'

services:
  nginx:
    build: 
      context: ./nginx/
      args:
        APP_ENV: prod
    image: loanpetit_nginx:latest
    container_name: loanpetit_nginx
    restart: always
    depends_on:
      - certbot
      - flutter
    volumes:
      - "certbot-conf:/etc/letsencrypt"
      - "certbot-www:/var/www/certbot"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"

  flutter:
    build: 
      context: ./flutter/
      args:
        FLUTTER_VERSION: v1.13.0
    image: loanpetit_flutter:latest
    container_name: loanpetit_flutter
    restart: always
    expose:
      - "80"

  certbot:
    image: certbot/certbot
    container_name: loanpetit_certbot
    restart: always
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - "certbot-conf:/etc/letsencrypt"
      - "certbot-www:/var/www/certbot"

volumes:
  certbot-conf:
  certbot-www:
