name: portfolio
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  url_launcher: ^5.4.1
  clipboard_manager: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - ./assets/png/
    - ./assets/social/

  fonts:
    - family: OpenSans
      fonts:
        - asset: ./fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
          style: normal
        - asset: ./fonts/OpenSans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: ./fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
          style: normal
        - asset: ./fonts/OpenSans/OpenSans-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: ./fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
          style: normal
        - asset: ./fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: ./fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
          style: normal
        - asset: ./fonts/OpenSans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: ./fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: ./fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
