name: portfolio
description: Portfolio app for Loan PETIT.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - ./assets/png/
    - ./assets/social/

  fonts:
    - family: OpenSans
      fonts:
        - asset: ./fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
          style: normal
        - asset: ./fonts/OpenSans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: ./fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
          style: normal
        - asset: ./fonts/OpenSans/OpenSans-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: ./fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
          style: normal
        - asset: ./fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: ./fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
          style: normal
        - asset: ./fonts/OpenSans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: ./fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: ./fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
